REFERER_LINK_PARAMETER = 'refer'
REFERER_DEFAULT_ID = 1
# ?refer=1

REFERER_MODEL_FROM = 'django.contrib.auth.models'
REFERER_MODEL_IMPORT = 'User'
# from REFERER_MODEL_FROM import REFERER_MODEL_IMPORT

REFERER_IGNORED_LINKS = []
